"""003 — market data infrastructure

Canonical market model (trading_calendar, stock_master, daily_prices,
index_quotes, institutional_flow, corporate_actions, market_status) plus the
data-operations tables that make it trustworthy (data_sources, raw_ingestions,
data_quarantine, data_freshness, backfill_checkpoints, ingestion_metrics).

The users diff in here is not a schema change: migration 0002 created the
constraints one way and the model described them another. This aligns the model
with what is already in the database so `alembic check` reports no drift.

Revision ID: 0003_market_data_infrastructure
Revises: 0002_platform_and_users
Create Date: 2026-08-16
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003_market_data_infrastructure"
down_revision: str | None = "0002_platform_and_users"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backfill_checkpoints",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_key", sa.String(length=120), nullable=False),
        sa.Column("dataset", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("range_start", sa.Date(), nullable=False),
        sa.Column("range_end", sa.Date(), nullable=False),
        sa.Column("cursor", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("units_total", sa.Integer(), nullable=True),
        sa.Column("units_done", sa.Integer(), nullable=False),
        sa.Column("units_failed", sa.Integer(), nullable=False),
        sa.Column("units_skipped", sa.Integer(), nullable=False),
        sa.Column("records_written", sa.BigInteger(), nullable=False),
        sa.Column("records_quarantined", sa.BigInteger(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("failed_units", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','PAUSED','COMPLETED','FAILED')",
            name=op.f("ck_backfill_checkpoints_backfill_status_allowed"),
        ),
        sa.CheckConstraint(
            "cursor >= range_start AND cursor <= range_end + 1",
            name=op.f("ck_backfill_checkpoints_cursor_within_range"),
        ),
        sa.CheckConstraint(
            "range_end >= range_start", name=op.f("ck_backfill_checkpoints_range_ordered")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backfill_checkpoints")),
        sa.UniqueConstraint("job_key", name=op.f("uq_backfill_checkpoints_job_key")),
    )
    op.create_index(
        "ix_backfill_dataset", "backfill_checkpoints", ["dataset", "status"], unique=False
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("action_type", sa.String(length=30), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("announced_at_is_estimated", sa.Boolean(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("cash_dividend", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("stock_dividend", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("split_ratio", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("subscription_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("subscription_ratio", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("factor", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("ingestion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action_type IN ('CASH_DIVIDEND','STOCK_DIVIDEND','SPLIT','REVERSE_SPLIT','RIGHTS_ISSUE','CAPITAL_REDUCTION','PAR_VALUE_CHANGE')",
            name=op.f("ck_corporate_actions_action_type_allowed"),
        ),
        sa.CheckConstraint("factor > 0", name=op.f("ck_corporate_actions_factor_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
        sa.UniqueConstraint(
            "symbol", "action_type", "ex_date", "source", name="uq_corporate_actions_key"
        ),
    )
    op.create_index(
        "ix_corporate_actions_pit", "corporate_actions", ["symbol", "announced_at"], unique=False
    )
    op.create_index(
        "ix_corporate_actions_symbol", "corporate_actions", ["symbol", "ex_date"], unique=False
    )
    op.create_table(
        "daily_prices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("high", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("low", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("close", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("change", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("turnover", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("trade_count", sa.BigInteger(), nullable=True),
        sa.Column("adjust_factor", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("adjusted_close", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("adjusted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_suspended", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=20), nullable=True),
        sa.Column("quality_status", sa.String(length=10), nullable=False),
        sa.Column("quality_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("ingestion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality_status IN ('OK','SUSPECT','INVALID')",
            name=op.f("ck_daily_prices_quality_status_allowed"),
        ),
        sa.CheckConstraint(
            "symbol ~ '^[0-9A-Z]{4,10}$'", name=op.f("ck_daily_prices_symbol_format")
        ),
        sa.CheckConstraint(
            "high IS NULL OR close IS NULL OR high >= close",
            name=op.f("ck_daily_prices_high_ge_close"),
        ),
        sa.CheckConstraint(
            "high IS NULL OR low IS NULL OR high >= low", name=op.f("ck_daily_prices_high_ge_low")
        ),
        sa.CheckConstraint(
            "high IS NULL OR open IS NULL OR high >= open",
            name=op.f("ck_daily_prices_high_ge_open"),
        ),
        sa.CheckConstraint(
            "low IS NULL OR close IS NULL OR low <= close",
            name=op.f("ck_daily_prices_low_le_close"),
        ),
        sa.CheckConstraint(
            "low IS NULL OR open IS NULL OR low <= open", name=op.f("ck_daily_prices_low_le_open")
        ),
        sa.CheckConstraint(
            "turnover IS NULL OR turnover >= 0", name=op.f("ck_daily_prices_turnover_non_negative")
        ),
        sa.CheckConstraint(
            "volume IS NULL OR volume >= 0", name=op.f("ck_daily_prices_volume_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_prices")),
        sa.UniqueConstraint("symbol", "trading_date", "source", name="uq_daily_prices_key"),
    )
    op.create_index("ix_daily_prices_date", "daily_prices", ["trading_date"], unique=False)
    op.create_index("ix_daily_prices_quality", "daily_prices", ["quality_status"], unique=False)
    op.create_index(
        "ix_daily_prices_symbol_date", "daily_prices", ["symbol", "trading_date"], unique=False
    )
    op.create_table(
        "data_freshness",
        sa.Column("dataset", sa.String(length=50), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("expected_lag_minutes", sa.Integer(), nullable=False),
        sa.Column("expected_frequency", sa.String(length=20), nullable=False),
        sa.Column("last_data_date", sa.Date(), nullable=True),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_next_update", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_count", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("lag_minutes", sa.Integer(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('FRESH','STALE','MISSING','DEGRADED')",
            name=op.f("ck_data_freshness_freshness_status_allowed"),
        ),
        sa.CheckConstraint(
            "expected_lag_minutes > 0", name=op.f("ck_data_freshness_expected_lag_positive")
        ),
        sa.PrimaryKeyConstraint("dataset", name=op.f("pk_data_freshness")),
    )
    op.create_table(
        "data_quarantine",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dataset", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("trading_date", sa.Date(), nullable=True),
        sa.Column("raw_record", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized_record", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rule_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("ingestion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(length=30), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "resolution IS NULL OR resolution IN ('ACCEPTED','DISCARDED','SOURCE_FIXED','REINGESTED')",
            name=op.f("ck_data_quarantine_resolution_allowed"),
        ),
        sa.CheckConstraint(
            "severity IN ('FATAL','WARN')", name=op.f("ck_data_quarantine_severity_allowed")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quarantine")),
    )
    op.create_index(
        "ix_quarantine_dataset", "data_quarantine", ["dataset", "created_at"], unique=False
    )
    op.create_index(
        "ix_quarantine_review", "data_quarantine", ["reviewed_at", "dataset"], unique=False
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("provider_type", sa.String(length=30), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=True),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("frequency", sa.String(length=30), nullable=True),
        sa.Column("requires_auth", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("rate_limit_per_day", sa.Integer(), nullable=True),
        sa.Column("max_concurrency", sa.SmallInteger(), nullable=False),
        sa.Column("min_interval_ms", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_retries", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("licence", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','DEGRADED','DISABLED','UNVERIFIED')",
            name=op.f("ck_data_sources_status_allowed"),
        ),
        sa.CheckConstraint(
            "max_concurrency > 0", name=op.f("ck_data_sources_concurrency_positive")
        ),
        sa.CheckConstraint("rate_limit_per_minute > 0", name=op.f("ck_data_sources_rpm_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("code", name=op.f("uq_data_sources_code")),
    )
    op.create_table(
        "index_quotes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("index_code", sa.String(length=40), nullable=False),
        sa.Column("index_name", sa.String(length=100), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("index_type", sa.String(length=20), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("high", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("low", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("close", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("change", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("change_pct", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("turnover", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("quality_status", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("ingestion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "index_type IN ('MARKET','INDUSTRY','SECTOR','THEMATIC')",
            name=op.f("ck_index_quotes_index_type_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_quotes")),
        sa.UniqueConstraint("index_code", "trading_date", "source", name="uq_index_quotes_key"),
    )
    op.create_index(
        "ix_index_quotes_code_date", "index_quotes", ["index_code", "trading_date"], unique=False
    )
    op.create_index("ix_index_quotes_date", "index_quotes", ["trading_date"], unique=False)
    op.create_table(
        "ingestion_metrics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dataset", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=True),
        sa.Column("provider_ms", sa.Integer(), nullable=True),
        sa.Column("parse_ms", sa.Integer(), nullable=True),
        sa.Column("validation_ms", sa.Integer(), nullable=True),
        sa.Column("persist_ms", sa.Integer(), nullable=True),
        sa.Column("total_ms", sa.Integer(), nullable=True),
        sa.Column("records_in", sa.Integer(), nullable=False),
        sa.Column("records_written", sa.Integer(), nullable=False),
        sa.Column("records_quarantined", sa.Integer(), nullable=False),
        sa.Column("rows_per_second", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("ingestion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_metrics")),
    )
    op.create_index(
        "ix_ingestion_metrics_dataset", "ingestion_metrics", ["dataset", "created_at"], unique=False
    )
    op.create_table(
        "institutional_flow",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("investor_type", sa.String(length=30), nullable=False),
        sa.Column("buy_volume", sa.BigInteger(), nullable=True),
        sa.Column("sell_volume", sa.BigInteger(), nullable=True),
        sa.Column("net_volume", sa.BigInteger(), nullable=True),
        sa.Column("buy_value", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("sell_value", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("net_value", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("quality_status", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("ingestion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "investor_type IN ('FOREIGN','FOREIGN_DEALER','INVESTMENT_TRUST','DEALER_SELF','DEALER_HEDGE','DEALER','TOTAL')",
            name=op.f("ck_institutional_flow_investor_type_allowed"),
        ),
        sa.CheckConstraint(
            "symbol ~ '^[0-9A-Z]{4,10}$'", name=op.f("ck_institutional_flow_symbol_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutional_flow")),
        sa.UniqueConstraint(
            "symbol", "trading_date", "investor_type", "source", name="uq_institutional_flow_key"
        ),
    )
    op.create_index(
        "ix_institutional_flow_date_type",
        "institutional_flow",
        ["trading_date", "investor_type"],
        unique=False,
    )
    op.create_index(
        "ix_institutional_flow_symbol_date",
        "institutional_flow",
        ["symbol", "trading_date"],
        unique=False,
    )
    op.create_table(
        "market_status",
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("last_trading_date", sa.Date(), nullable=True),
        sa.Column("next_trading_date", sa.Date(), nullable=True),
        sa.Column("is_trading_day_today", sa.Boolean(), nullable=True),
        sa.Column("session_type_today", sa.String(length=20), nullable=True),
        sa.Column("symbol_count", sa.Integer(), nullable=True),
        sa.Column("price_row_count", sa.BigInteger(), nullable=True),
        sa.Column("earliest_price_date", sa.Date(), nullable=True),
        sa.Column("latest_price_date", sa.Date(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("market", name=op.f("pk_market_status")),
    )
    op.create_table(
        "raw_ingestions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_endpoint", sa.String(length=255), nullable=False),
        sa.Column("dataset", sa.String(length=50), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("transport", sa.String(length=10), nullable=False),
        sa.Column("source_request_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_as_of", sa.Date(), nullable=True),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("response_bytes", sa.Integer(), nullable=True),
        sa.Column("response_hash", sa.String(length=64), nullable=True),
        sa.Column("storage_uri", sa.String(length=500), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("accepted_count", sa.Integer(), nullable=True),
        sa.Column("quarantined_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("job_run_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "status IN ('SUCCESS','PARTIAL','FAILED')",
            name=op.f("ck_raw_ingestions_ingestion_status_allowed"),
        ),
        sa.CheckConstraint(
            "transport IN ('LIVE','REPLAY','MOCK')",
            name=op.f("ck_raw_ingestions_transport_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_ingestions")),
    )
    op.create_index(
        "ix_raw_ingestions_as_of", "raw_ingestions", ["dataset", "data_as_of"], unique=False
    )
    op.create_index(
        "ix_raw_ingestions_dataset",
        "raw_ingestions",
        ["dataset", "source_request_at"],
        unique=False,
    )
    op.create_index("ix_raw_ingestions_hash", "raw_ingestions", ["response_hash"], unique=False)
    op.create_table(
        "stock_master",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("name_en", sa.String(length=150), nullable=True),
        sa.Column("short_name_en", sa.String(length=50), nullable=True),
        sa.Column("security_type", sa.String(length=20), nullable=False),
        sa.Column("industry_code", sa.String(length=10), nullable=True),
        sa.Column("industry_name", sa.String(length=50), nullable=True),
        sa.Column("sector", sa.String(length=50), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("delisting_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("par_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("paid_in_capital", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("shares_outstanding", sa.BigInteger(), nullable=True),
        sa.Column("tax_id", sa.String(length=20), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("ingestion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('LISTED','SUSPENDED','DELISTED')",
            name=op.f("ck_stock_master_status_allowed"),
        ),
        sa.CheckConstraint(
            "symbol ~ '^[0-9A-Z]{4,10}$'", name=op.f("ck_stock_master_symbol_format")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_stock_master_validity_window"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_master")),
    )
    op.create_index("ix_stock_master_industry", "stock_master", ["industry_code"], unique=False)
    op.create_index(
        "ix_stock_master_symbol", "stock_master", ["symbol", "valid_from"], unique=False
    )
    op.create_index(
        "uq_stock_master_current",
        "stock_master",
        ["symbol", "market"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "trading_calendar",
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("calendar_date", sa.Date(), nullable=False),
        sa.Column("is_trading_day", sa.Boolean(), nullable=False),
        sa.Column("session_type", sa.String(length=20), nullable=False),
        sa.Column("holiday_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("verified_by_volume", sa.Boolean(), nullable=False),
        sa.Column("observed_symbol_count", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(is_trading_day AND session_type IN ('FULL','HALF')) OR (NOT is_trading_day AND session_type IN ('CLOSED','SETTLEMENT_ONLY'))",
            name=op.f("ck_trading_calendar_trading_day_matches_session"),
        ),
        sa.CheckConstraint(
            "session_type IN ('FULL','HALF','CLOSED','SETTLEMENT_ONLY')",
            name=op.f("ck_trading_calendar_session_type_allowed"),
        ),
        sa.PrimaryKeyConstraint("market", "calendar_date", name=op.f("pk_trading_calendar")),
    )
    op.create_index(
        "ix_trading_calendar_trading",
        "trading_calendar",
        ["market", "calendar_date", "is_trading_day"],
        unique=False,
    )
    op.alter_column(
        "job_runs",
        "retry_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("ck_users_ck_users_role_allowed"), "users", type_="check")
    op.create_check_constraint(
        op.f("ck_users_role_allowed"), "users", "role IN ('admin','analyst','viewer')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_role_allowed"), "users", type_="check")
    op.create_check_constraint(
        op.f("ck_users_ck_users_role_allowed"),
        "users",
        "role::text = ANY (ARRAY['admin'::character varying, 'analyst'::character varying, 'viewer'::character varying]::text[])",
    )
    op.alter_column(
        "users",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'viewer'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "job_runs",
        "retry_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.drop_index("ix_trading_calendar_trading", table_name="trading_calendar")
    op.drop_table("trading_calendar")
    op.drop_index(
        "uq_stock_master_current", table_name="stock_master", postgresql_where=sa.text("is_current")
    )
    op.drop_index("ix_stock_master_symbol", table_name="stock_master")
    op.drop_index("ix_stock_master_industry", table_name="stock_master")
    op.drop_table("stock_master")
    op.drop_index("ix_raw_ingestions_hash", table_name="raw_ingestions")
    op.drop_index("ix_raw_ingestions_dataset", table_name="raw_ingestions")
    op.drop_index("ix_raw_ingestions_as_of", table_name="raw_ingestions")
    op.drop_table("raw_ingestions")
    op.drop_table("market_status")
    op.drop_index("ix_institutional_flow_symbol_date", table_name="institutional_flow")
    op.drop_index("ix_institutional_flow_date_type", table_name="institutional_flow")
    op.drop_table("institutional_flow")
    op.drop_index("ix_ingestion_metrics_dataset", table_name="ingestion_metrics")
    op.drop_table("ingestion_metrics")
    op.drop_index("ix_index_quotes_date", table_name="index_quotes")
    op.drop_index("ix_index_quotes_code_date", table_name="index_quotes")
    op.drop_table("index_quotes")
    op.drop_table("data_sources")
    op.drop_index("ix_quarantine_review", table_name="data_quarantine")
    op.drop_index("ix_quarantine_dataset", table_name="data_quarantine")
    op.drop_table("data_quarantine")
    op.drop_table("data_freshness")
    op.drop_index("ix_daily_prices_symbol_date", table_name="daily_prices")
    op.drop_index("ix_daily_prices_quality", table_name="daily_prices")
    op.drop_index("ix_daily_prices_date", table_name="daily_prices")
    op.drop_table("daily_prices")
    op.drop_index("ix_corporate_actions_symbol", table_name="corporate_actions")
    op.drop_index("ix_corporate_actions_pit", table_name="corporate_actions")
    op.drop_table("corporate_actions")
    op.drop_index("ix_backfill_dataset", table_name="backfill_checkpoints")
    op.drop_table("backfill_checkpoints")
    # ### end Alembic commands ###
